### ISSUE TITLE
Decrease map's initial zoom by one notch to include Green Valley Ranch marker

### ISSUE THREAD

**Issue by githamm** [denverpost/homicide-report#42]
Tried adding "zoom: x" to:

init: function() {
        L.tileLayer(this.tile, {
            attribution: this.attribution,
            maxZoom: 16
        }).addTo(this.map);

but it didn't work. Didn't commit change to repo. Leaflet docs here: http://leafletjs.com/reference.html#control-zoom

**Comment by freejoe76** [comment]
Sorry this took so long. It's fixed and live: http://www.denverpost.com/denverhomicides
